sudo: false
language: python
python:
  - "2.7"
cache:
  directories:
    - $HOME/.pip-cache/

services:
  - redis-server

install:
  - pip install coveralls
  - pip install wheel
  - pip install -r requirements-dev.txt
  - pip install -e .

script:
  - py.test --cov=portia --cov-report=term

after_success:
  - coveralls

deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: smn
  password:
    secure: "to be replaced"
  on:
    tags: true
    all_branches: true
